config/routes.rb
Rails.application.routes.draw do


  scope "(:locale)", :locale => /en|de/ do
    # ***** Please put the routes here, so we can get a beautiful URL *****
    get 'items/edit'
    get 'items/index'
    get 'items/new'
    get 'items/show'
    get 'demo/view'
    get 'demo/artikel'
    get 'demo/datenschutz'
    get 'demo/galerie'
    get 'demo/hello'
    get 'demo/impressum'
    get 'demo/index'
    get 'demo/kontakt'
    get 'demo/konzerte'
    get 'demo/musik'
    get 'demo/shop'
    get 'demo/todo'


    get 'welcome/index'
    devise_for :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root 'welcome#index'

  end

  resources :items do
    member do
      patch :complete
    end
  end

  resources :concerts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # for changing the language
  protect_from_forgery

  before_action :set_locale

  # for the time in the calendar
  before_action :set_time_zone, if: :user_signed_in?

  private

  def set_time_zone
    Time.zone = current_user.time_zone
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale] = I18n.locale
  end

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to concerts_path, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: concerts_path }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to concerts_path, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: concerts_path }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:band, :place, :start_time)
    end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  def artikel
  end

  def datenschutz
  end

  def galerie
  end

  def hello
  end

  def impressum
  end

  def index
  end

  def kontakt
  end

  def konzerte
  end

  def musik
  end

  def shop
  end

  def todo
    @items = Item.all.order("created_at DESC")
    render 'items/index'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy, :complete]
  def index
     @items = Item.all.order("created_at DESC")
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      @items = Item.all.order("created_at DESC")
      render 'items/index'
    else
      render 'new'
    end
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    @items = Item.all.order("created_at DESC")
    render 'items/index'
  end

  def edit

  end

  def complete
    @item.update_attribute(:completed_at, Time.now)
    @items = Item.all.order("created_at DESC")
    render 'items/index'
  end

  def show

  end

  private

  def item_params
    params.require(:item).permit(:name, :description)
  end

  def find_item
    @item = Item.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/concerts/_form.html.erb
<%= simple_form_for(@concert) do |f| %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :band, label: t(:band)%>
    <%= f.input :place, label: t(:place) %>
    <%= f.input :start_time, label: t(:start_time)%>
  </div>

  <div class="form-actions">
    <%= f.submit t(:create)%>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1><%= t(:edit_concert) %></h1>

<%= render 'form', concert: @concert %>
<%= button_to t(:show), @concert, :method => "get" %>
<%= button_to t(:back), concerts_path, :method => "get" %>


<%= month_calendar(attribute: :starts_at) do |date| %>
  <%= date.day %>
<% end %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t(:'header.concerts') %></h1>
<%= month_calendar events: @concerts do |date, concerts| %>
  <%= date.day %>

  <% concerts.each do |concert| %>
    <div>
      <%= concert.band %>
    </div>
    <div>
      <%= concert.place %>
    </div>
    <div>
      <%= link_to t(:edit_concert), edit_concert_path(concert) %>
    </div>
    <div>
      <%= link_to t(:remove), concert, method: :delete, data: { confirm: t(:'edit.sure') } %>
    </div>
  <% end %>
<% end %>

<br>

<%= button_to t(:new_concert), new_concert_path, :method => "get" %>

app/views/concerts/new.html.erb
<h1><%= t(:new_concert) %></h1>

<%= render 'form', concert: @concert %>

<%= month_calendar(attribute: :starts_at) do |date| %>
  <%= date.day %>
<% end %>

<%= link_to t(:back), concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t(:band) %>:</strong>
  <%= @concert.band %>
</p>

<p>
  <strong><%= t(:place) %>:</strong>
  <%= @concert.place %>
</p>

<p>
  <strong><%= t(:start_time) %>:</strong>
  <%= @concert.start_time %>
</p>

<%= link_to t(:back), edit_concert_path(@concert) %>
<%= link_to t(:cancel), concerts_path %>

app/views/demo/artikel.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<h1><%= t(:'header.articles') %></h1>
</body>
</html>

app/views/demo/datenschutz.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<h1><%= t(:'footer.privacy') %></h1>
</body>
</html>

app/views/demo/galerie.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<h1><%= t(:'header.gallery') %></h1>
</body>
</html>

app/views/demo/hello.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<p> :)</p>
</body>
</html>

app/views/demo/impressum.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<h1><%= t(:'footer.imprint') %></h1>
</body>
</html>

app/views/demo/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>



</body>
</html>

app/views/demo/kontakt.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<h1><%= t(:'footer.contact') %></h1>
</body>
</html>

app/views/demo/konzerte.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<h1><%= t(:'header.concerts') %></h1>
</body>
</html>

app/views/demo/musik.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<h1><%= t(:'header.music') %></h1>
</body>
</html>

app/views/demo/shop.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<h1><%= t(:'header.shop') %></h1>
</body>
</html>

app/views/demo/todo.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Hello World
  </title>
</head>
<body>
<h1><%=t(:'header.wunschkonzert') %></h1>
</body>
</html>

app/views/items/edit.html.erb
<h1><%= t(:'edit.edit_concert') %></h1>

<%= simple_form_for @item do |f| %>
  <%= f.input :name, label: t(:'edit.task') %>
  <%= f.input :description, label: t(:'edit.description') %>
  <%= f.button :submit, t(:'edit.reedit') %>
<% end %>

app/views/items/index.html.erb
<div align="center"><h1><%=t(:i_wish_for)%></h1>
<br>
<p><%= t(:wishing_for_text_html) %></p>
<button type="button" class="btn btn-default"><%= link_to t(:new_concert), new_item_path %></button>
</div>
  <% @items.each do |item| %>
    <div class="row item" id="row">
      <% if item.completed? %>
        <div class="col-md-6">
          <h1><s><%= link_to item.name, item %></s></h1>
          <p><%= time_ago_in_words(item.completed_at) %> <%= t(:ago) %></p>
        </div>
        <div class="col-md-2">
        </div>
      <% else %>
        <div class="col-md-6">
          <h1><%= link_to item.name, item %></h1>
          <p><%= item.description %></p>
        </div>
        <div class="col-md-2">
          <%= link_to complete_item_path(item), method: :patch do %>
            <h2><%= t(:wish_fulfilled) %></h2>
          <% end %>
        </div>
      <% end %>
    </div>
<% end %>

app/views/items/new.html.erb
<h1><%= t(:'edit.add') %></h1>

<%= simple_form_for @item do |f| %>
  <%= f.input :name, label: t(:'edit.concert') %>
  <%= f.input :description, label: t(:'edit.description') %>
  <%= f.button :submit, t(:'edit.create') %>
<% end %>

app/views/items/show.html.erb
<h2><%= @item.name %></h2>
<p><%= @item.description %></p>

<%= link_to t(:'edit.return'),'index' %>

<%= link_to t(:'edit.reedit'), edit_item_path %>

<%= link_to t(:'edit.delete') , item_path(@item), method: :delete, data: {confirm: t(:'edit.sure')}%>

app/views/layouts/_footer.html.erb
<table id="footer">
  <td><p><%= link_to(t(:'footer.imprint'),demo_impressum_path) %> |</p></td>
  <td><p><%= link_to(t(:'footer.privacy'),demo_datenschutz_path) %> |</p></td>
  <td><p><%= link_to(t(:'footer.contact'),demo_kontakt_path) %> </p></td>
</table>

app/views/layouts/_header.html.erb
<table id="header">
  <td><p><%= link_to(t(:'header.home'), welcome_index_path) %> |</p></td>
  <td><p><%= link_to(t(:'header.articles'), demo_artikel_path )%> |</p></td>
  <td><p><%= link_to(t(:'header.gallery'),demo_galerie_path) %> |</p></td>
  <td><p><%= link_to(t(:'header.music'),demo_musik_path) %> |</p></td>
  <td><p><%= link_to(t(:'header.concerts'),concerts_path) %> |</p></td>
  <td><p><%= link_to(t(:'header.shop'),demo_shop_path) %> |</p></td>
  <td><p><%= link_to(t(:'header.wunschkonzert'),demo_todo_path) %></p></td>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="container">
  <div  id="table" align="center">
    <table>
      <tr>
        <td><div id="log">
          <% if user_signed_in? %>
            <%= link_to( t(:'application.log_out'), destroy_user_session_path, method: :delete) %>
          <% else %>
            <%= link_to( t(:log_in), new_user_session_path) %>
          <% end %>
        </div> </td>
        <td><div id="head"><%=render "layouts/header"%></div></td>
        <td>   <!--So the user can change the language Settings in the Browser -->
          <div id="engDeu">
            <%= link_to_unless I18n.locale == :en, "English", locale: :en %>
            |
            <%= link_to_unless I18n.locale == :de, "Deutsch", locale: :de %>
          </div>  </td>
      </tr>
    </table></div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  <%=render "layouts/footer" %>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<h1><%= t(:'index.welcome')%></h1>
<p><%= t(:'index.enjoy')%></p>